server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  data:
    rest:
      basePath: /api
  logging:
    level:
      org.springframework.security: DEBUG
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org:
      zalando:
        logbook: TRACE

lab:
  jwtPublicKey: |
                -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz8Y+umAvSQKgOHq4FbIg
                RSfJ436ItzpQ1SsdbO1QDjMxgl7od5wWOUvf4F0qk0Z93ZmZuQopKQysYRazkGd2
                UvVq3edh79BNET5okG3IuX+4gfhC8W1BgpP6BQlF61w0Q86u/4ey7fXWcWRUX4+g
                pC2D7bgUsAwbtGATFJzF9+0Tp3MWj6+tZa6jmiDah8Jpds++NVDu07jsLw/AvyO2
                jaqjr5Fdk7MX8DWFVPebliT/UKijEru6uJ2u5xn9YDWYpxbRGq6pipcqQj/Icvvz
                bh5+lyLaB1foRiOSm4q9MMmG6q+KIxPLhytg/GYokHqA7pUgFqWOlFmVvSMwzeWd
                8QIDAQAB
                -----END PUBLIC KEY-----
  audience: webapp